### ISSUE TITLE
[Bug]: running galaxy-flasher.py fails on Ubuntu MATE

### ISSUE THREAD

**Issue by netsmile** [ethical-haquer/Galaxy-Flasher#20]
### What happened?

csaba@Normandy:~/Desktop/TABLET FIX/DotOS/Tools/galaxy-flasher-v0.5.1-alpha-linux$ python3 galaxy-flasher.py
Traceback (most recent call last):
  File "/home/csaba/Desktop/TABLET FIX/DotOS/Tools/galaxy-flasher-v0.5.1-alpha-linux/galaxy-flasher.py", line 32, in <module>
    gi.require_version("Adw", "1")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available

### Galaxy Flasher version

Alpha v0.5.1

**Comment by ethical-haquer** [comment]
@netsmile
Hey!
What distro are you using?

**Comment by netsmile** [comment]
Linux 5.15.0-119-generic x86_64
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

**Comment by netsmile** [comment]
[libadwaita-1-0](https://packages.ubuntu.com/jammy/libadwaita-1-0) installed
Error remains.

**Comment by ethical-haquer** [comment]
@netsmile 
Hmm.
Try installing the `libadwaita-1-dev` package as well.

**Comment by ethical-haquer** [comment]
Vte is not a dependency anymore in v0.6.0.

**Comment by ethical-haquer** [comment]
Any update on this?

**Comment by netsmile** [comment]
I just tried by reinstalling via flatpack the latest version and it works now. 
Thanks

**Comment by ethical-haquer** [comment]
@netsmile 
No problem, thanks for the reply.
Alpha v0.6.0 then?

**Comment by ethical-haquer** [comment]
Hello @netsmile!
I'm closing this issue, as I'm getting ready to archive this GitHub repo.
If you don't already have one, you might want to make a [Codeberg](https://codeberg.org/) account, as that is [where Galaxy Flasher's code will be hosted now](https://codeberg.org/ethical_haquer/Galaxy-Flasher). However, you can also use your GitHub account to sign into Codeberg, if you don't want to make a Codeberg one.

I'm shifting away from GitHub because it just doesn't make sense to host open-source projects on a proprietary platform.
If you have any questions/comments, feel free to post them here! 🙂
I'll wait a little while before archiving this repo.

**Comment by ethical-haquer** [comment]
Closing this issue as this repo is now archived.
